# Global options:

[mypy]

ignore_missing_imports = True
python_version = 3.12
exclude = (?x)(
    .*meson.*
  )

[mypy-numcosmo_py.nc]

ignore_errors = True

[mypy-numcosmo_py.ncm]

ignore_errors = True

