# Global options:

[mypy]

ignore_missing_imports = True
check_untyped_defs = True
python_version = 3.12
exclude = (?x)(
    .*meson.*
    | numcosmo_py/external/
  )

[mypy-numcosmo_py.nc]

ignore_errors = True

[mypy-numcosmo_py.ncm]

ignore_errors = True

[mypy-numcosmo_py.external.*]

ignore_errors = True
