version: 2

conda:
  environment: devel_environment.yml

build:
  os: ubuntu-24.04
  tools:
    # Because we are using python: miniconda-latest, we will be using conda
    # instead of conda.
    python: mambaforge-latest
  jobs:
    pre_build:
      - echo $PATH
      - conda info
      - conda env list  
      - meson setup build -Ddocumentation=true -Db_lto=false
      - meson compile -C build
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - mv build/docs/numcosmo-site/* $READTHEDOCS_OUTPUT/html/.

# Debug line
#     - . build/numcosmo_export.sh; PATH="$HOME/opt/quarto-1.8.25/bin:$PATH" conda run -n numcosmo_developer quarto render build/docs --output-dir test-site --execute-debug --log-level debug --no-cache --execute-daemon-restart --debug
