version: 2

conda:
  environment: devel_environment.yml

build:
  os: ubuntu-22.04
  tools:
    # Because we are using python: mambaforge-latest, we will be using mamba
    # instead of conda.
    python: mambaforge-latest
  commands:
    - mamba env remove -n numcosmo_developer -q || true
    - mamba env create --file devel_environment.yml
    - mamba install -n numcosmo_developer -y gi-docgen jupyter plotnine tabulate
    - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.7.6/quarto-1.7.6-linux-amd64.tar.gz && mkdir ~/opt && tar -C ~/opt -xvzf quarto-1.7.6-linux-amd64.tar.gz
    - PATH="$HOME/opt/quarto-1.7.6/bin:$PATH" mamba run -n numcosmo_developer meson setup build -Ddocumentation=true -Db_lto=false 
    - mamba run -n numcosmo_developer meson compile -C build
    - source build/numcosmo_export.sh; mamba run -n numcosmo_developer quarto render --output-dir test-site
    - cat build/numcosmo-site.log
    - find .
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - mv build/docs/numcosmo-site/* $READTHEDOCS_OUTPUT/html/.
