version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "latest"
  jobs:
    pre_build:
      - pip install requests
    build:
      html:
        - python -u docs/download_docs_site.py
        - mkdir --parents $READTHEDOCS_OUTPUT/html/
        - mv numcosmo-site/* $READTHEDOCS_OUTPUT/html/.


