version: 2

conda:
  environment: devel_environment.yml

build:
  os: ubuntu-24.04
  tools:
    # Because we are using python: miniconda-latest, we will be using conda
    # instead of conda.
    python: miniconda-latest
  commands:
    - conda env update --file devel_environment.yml --prune
    - conda install -n numcosmo_developer -y gi-docgen plotnine tabulate quarto nbformat nbclient jupyter jupyterlab nbconvert ipykernel
    - conda run -n numcosmo_developer meson setup build -Ddocumentation=true -Db_lto=false
    - conda run -n numcosmo_developer meson compile -C build || cat build/numcosmo-site.log
    - . build/numcosmo_export.sh; conda run -n numcosmo_developer quarto render build/docs --output-dir test-site --execute-debug --log-level debug --no-cache --execute-daemon-restart --debug
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - mv build/docs/numcosmo-site/* $READTHEDOCS_OUTPUT/html/.

# Debug line
#     - . build/numcosmo_export.sh; PATH="$HOME/opt/quarto-1.8.25/bin:$PATH" conda run -n numcosmo_developer quarto render build/docs --output-dir test-site --execute-debug --log-level debug --no-cache --execute-daemon-restart --debug
