/* -*- Mode: C; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*-  */

/***************************************************************************
 *            ncm_stats_dist_kde.c
 *
 *  Wed November 07 16:02:36 2018
 *  Copyright  2018  Sandro Dias Pinto Vitenti
 *  <sandro@isoftware.com.br>
 ****************************************************************************/
/*
 * ncm_stats_dist_kde.c
 * Copyright (C) 2018 Sandro Dias Pinto Vitenti <sandro@isoftware.com.br>
 *
 * numcosmo is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * numcosmo is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * SECTION:ncm_stats_dist_kde
 * @title: NcmStatsDistKDE
 * @short_description: Abstract class for implementing N dimensional probability distributions
 *
 * Abstract class to reconstruct an arbitrary N dimensional probability distribution.
 * This object provides the tools to perform a radial basis interpolation
 * in a multidimensional function using a radial basis function.
 * The goal is to use a polynomial function generated by the interpolation,
 * such that we are able to sample the original function from this new interpolation function.
 * For more informations about radial basis interpolation,
 * check [[Radial Basis Function Interpolation, Wilna du Toit](https://core.ac.uk/download/pdf/37320748.pdf)].
 * A brief description of the radial basis interpolation method can be found below.
 *
 * Given a d-simensional function $g(x): \mathbf{R}^d \rightarrow \mathbf{R}$, a radial basis
 * function $\phi(x)$ is used such that
 * \begin{align}
 * \label{Interpolation_eq}
 * s(x) = \sum_i^n \lambda \phi(|x-xi|), \quad x~ \in~ \mathbf{R}
 *. \end{align}
 * The matrix lambda is found such that $s(x_i) = g(x_i)$, being $x_i$ the sample points.
 * The points $\phi(|x-x_i|)$ generate a symmetric $n \times n$ matrix using a radial basis function.
 * Once the Lambda matrix is found, one may use $s(x)$ to sample values from $g(x)$, which is easier to do since $s(x)$ is
 * a polynomial function.
 *
 * We want $s(x)$ to be a probability function so we can sample from it. Therefore the Lambda matrix containing the
 * weights is seen as the probability density of our probability function and it must be minimized
 * such that its values are always positive and sum up to one. To solve this problem, this algorithm has the tools to solve equation \eqref{Interpolation_eq} for $\lambda$
 * using the LowRankQP method, the NNLS method or the Libqp method.
 * These methods can be found in the LowRankQP.c, nnls.c and libqp_plx.c files respectively.
 *
 * In this file, the radial basis interpolation function is not defined. One must choose one of the instances of the class, the
 * #NcmStatsDistKDEKDEStudentt object or the #NcmStatsDistKDEKDEGauss object, which use a multivariate Student's t function and a Gaussian function respectively.
 * After initializing the desired object for the interpolation function, one may use the methods of this file to generate the interpolation and to
 * sample from the new interpolated function.
 *
 * The user must provide input the values: over_smooth - ncm_stats_dist_kde_set_over_smooth(), $v(x)$ - ncm_stats_dist_kde_prepare_interp(). The other parameters are
 * automatically calculated when the instance for the Gauss or the Student's t functions is initialized.
 *
 *
 *
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "build_cfg.h"

#include "math/ncm_stats_dist_kde.h"
#include "math/ncm_iset.h"
#include "math/ncm_nnls.h"
#include "math/ncm_lapack.h"
#include "ncm_enum_types.h"

#ifndef NUMCOSMO_GIR_SCAN
#include <gsl/gsl_blas.h>
#include "levmar/levmar.h"
#endif /* NUMCOSMO_GIR_SCAN */

#include "math/ncm_stats_dist_kde_private.h"

enum
{
  PROP_0,
  PROP_NEARPD_MAXITER,
};

G_DEFINE_ABSTRACT_TYPE_WITH_PRIVATE (NcmStatsDistKDE, ncm_stats_dist_kde, NCM_TYPE_STATS_DIST);

static void
ncm_stats_dist_kde_init (NcmStatsDistKDE *sdkde)
{
  NcmStatsDistKDEPrivate * const self = sdkde->priv = ncm_stats_dist_kde_get_instance_private (sdkde);
  
  self->sample         = NULL;
  self->cov_decomp     = NULL;
  self->sample_matrix  = NULL;
  self->invUsample     = g_ptr_array_new ();
  self->v              = NULL;
  self->href           = 0.0;
  self->kernel_lnnorm  = 0.0;
  self->min_m2lnp      = 0.0;
  self->max_m2lnp      = 0.0;
  self->m2lnp_stats    = ncm_stats_vec_new (1, NCM_STATS_VEC_MEAN, FALSE);
  self->rnorm          = 0.0;
  self->n              = 0;
  self->alloc_n        = 0;
  self->d              = 0;
  self->sampling       = g_array_new (FALSE, FALSE, sizeof (guint));
  self->nearPD_maxiter = 0;
  
  ncm_stats_vec_enable_quantile (self->m2lnp_stats, 0.9999); /* 0.6827, 0.9545, 0.9973 */
  
  g_ptr_array_set_free_func (self->invUsample, (GDestroyNotify) ncm_vector_free);
}

static void
_ncm_stats_dist_kde_set_property (GObject *object, guint prop_id, const GValue *value, GParamSpec *pspec)
{
  NcmStatsDistKDE *sdkde = NCM_STATS_DIST_KDE (object);
  
  /*g_return_if_fail (NCM_IS_STATS_DIST_KDE (object));*/
  
  switch (prop_id)
  {
    case PROP_NEARPD_MAXITER:
      ncm_stats_dist_kde_set_nearPD_maxiter (sdkde, g_value_get_uint (value));
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
}

static void
_ncm_stats_dist_kde_get_property (GObject *object, guint prop_id, GValue *value, GParamSpec *pspec)
{
  NcmStatsDistKDE *sdkde              = NCM_STATS_DIST_KDE (object);
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  
  g_return_if_fail (NCM_IS_STATS_DIST_KDE (object));
  
  switch (prop_id)
  {
    case PROP_NEARPD_MAXITER:
      g_value_set_uint (value, self->nearPD_maxiter);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
}

static void
_ncm_stats_dist_kde_dispose (GObject *object)
{
  NcmStatsDistKDE *sdkde              = NCM_STATS_DIST_KDE (object);
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  
  ncm_stats_vec_clear (&self->sample);
  ncm_matrix_clear (&self->cov_decomp);
  ncm_matrix_clear (&self->sample_matrix);
  ncm_vector_clear (&self->v);
  
  g_clear_pointer (&self->sampling, g_array_unref);
  g_clear_pointer (&self->invUsample, g_ptr_array_unref);
  
  ncm_stats_vec_clear (&self->m2lnp_stats);
  
  /* Chain up : end */
  G_OBJECT_CLASS (ncm_stats_dist_kde_parent_class)->dispose (object);
}

static void
_ncm_stats_dist_kde_finalize (GObject *object)
{
  /*NcmStatsDistKDE *sdkde = NCM_STATS_DIST_KDE (object);*/
  /*NcmStatsDistKDEPrivate * const self = sdkde->priv;*/
  
  /* Chain up : end */
  G_OBJECT_CLASS (ncm_stats_dist_kde_parent_class)->finalize (object);
}

static void _ncm_stats_dist_kde_set_dim (NcmStatsDist *sd, const guint dim);
static void _ncm_stats_dist_kde_prepare_kernel (NcmStatsDist *sd, GPtrArray *sample_array);

static void
ncm_stats_dist_kde_class_init (NcmStatsDistKDEClass *klass)
{
  GObjectClass *object_class  = G_OBJECT_CLASS (klass);
  NcmStatsDistClass *sd_class = NCM_STATS_DIST_CLASS (klass);
  
  object_class->set_property = &_ncm_stats_dist_kde_set_property;
  object_class->get_property = &_ncm_stats_dist_kde_get_property;
  object_class->dispose      = &_ncm_stats_dist_kde_dispose;
  object_class->finalize     = &_ncm_stats_dist_kde_finalize;
  
  g_object_class_install_property (object_class,
                                   PROP_NEARPD_MAXITER,
                                   g_param_spec_uint ("nearPD-maxiter",
                                                      NULL,
                                                      "Maximum number of iterations in the nearPD call",
                                                      1, G_MAXUINT, 200,
                                                      G_PARAM_READWRITE | G_PARAM_CONSTRUCT | G_PARAM_STATIC_NAME | G_PARAM_STATIC_BLURB));
  
  sd_class->set_dim        = &_ncm_stats_dist_kde_set_dim;
  sd_class->prepare_kernel = &_ncm_stats_dist_kde_prepare_kernel;
}

static void
_ncm_stats_dist_kde_set_dim (NcmStatsDist *sd, const guint dim)
{
  /* Chain up : start */
  NCM_STATS_DIST_CLASS (ncm_stats_dist_kde_parent_class)->set_dim (sd, dim);
  {
    NcmStatsDistKDE *sdkde              = NCM_STATS_DIST_KDE (sd);
    NcmStatsDistKDEPrivate * const self = sdkde->priv;
    
    ncm_stats_vec_clear (&self->sample);
    
    ncm_matrix_clear (&self->cov_decomp);
    ncm_matrix_clear (&self->sample_matrix);
    ncm_vector_clear (&self->v);
    
    self->sample     = ncm_stats_vec_new (dim, NCM_STATS_VEC_COV, TRUE);
    self->cov_decomp = ncm_matrix_new (dim, dim);
    self->v          = ncm_vector_new (dim);
  }
}

static void
_cholesky_decomp (NcmMatrix *cov_decomp, NcmMatrix *cov, const guint d, const guint maxiter)
{
  ncm_matrix_memcpy (cov_decomp, cov);
  
  if (ncm_matrix_cholesky_decomp (cov_decomp, 'U') != 0)
  {
    ncm_matrix_memcpy (cov_decomp, cov);
    
    if (ncm_matrix_nearPD (cov_decomp, 'U', TRUE, maxiter) != 0)
    {
      gint i;
      
      ncm_matrix_set_zero (cov_decomp);
      
      for (i = 0; i < d; i++)
      {
        ncm_matrix_set (cov_decomp, i, i, ncm_matrix_get (cov, i, i));
      }
      
      g_assert_cmpint (ncm_matrix_cholesky_decomp (cov_decomp, 'U'), ==, 0);
    }
  }
}

static void
_ncm_stats_dist_kde_prepare_kernel (NcmStatsDist *sd, GPtrArray *sample_array)
{
  NcmStatsDistKDE *sdkde = NCM_STATS_DIST_KDE (sd);
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  NcmStatsDistKernel *kernel = ncm_stats_dist_peek_kernel (sd);
  gint i, ret;
  
  self->n = sample_array->len;
  g_assert_cmpuint (self->n, >, 1);
  
  /*
   * Computing the covariance matrix considering the whole sample.
   */
  ncm_stats_vec_reset (self->sample, TRUE);
  
  for (i = 0; i < self->n; i++)
  {
    NcmVector *theta_i = g_ptr_array_index (sample_array, i);
    
    ncm_stats_vec_append (self->sample, theta_i, FALSE);
  }
  
  /*
   * Computing the Cholesky decomposition of the total covariance.
   */
  _cholesky_decomp (self->cov_decomp, ncm_stats_vec_peek_cov_matrix (self->sample, 0), self->d, self->nearPD_maxiter);
  
  /*
   * Getting kernel normalization
   */
  self->kernel_lnnorm = ncm_stats_dist_kernel_get_lnnorm (kernel, self->cov_decomp, self->href);
  
  if ((self->sample_matrix == NULL) || (self->n != ncm_matrix_nrows (self->sample_matrix)) || (self->d != ncm_matrix_ncols (self->sample_matrix)))
  {
    ncm_matrix_clear (&self->sample_matrix);
    self->sample_matrix = ncm_matrix_new (self->n, self->d);
    
    g_ptr_array_set_size (self->invUsample, 0);
    
    for (i = 0; i < self->n; i++)
    {
      NcmVector *row_i = ncm_matrix_get_row (self->sample_matrix, i);
      
      g_ptr_array_add (self->invUsample, row_i);
    }
  }
  
  for (i = 0; i < self->n; i++)
    ncm_matrix_set_row (self->sample_matrix, i, ncm_stats_vec_peek_row (self->sample, i));
  
  ret = gsl_blas_dtrsm (CblasRight, CblasUpper, CblasNoTrans, CblasNonUnit, 1.0, ncm_matrix_gsl (self->cov_decomp), ncm_matrix_gsl (self->sample_matrix));
  NCM_TEST_GSL_RESULT ("_ncm_stats_dist_kde_prepare_kernel", ret);
}

/**
 * ncm_stats_dist_kde_new:
 * @sdk: a #NcmStatsDistKernel
 * @CV_type: a #NcmStatsDistCV
 *
 * Creates a new #NcmStatsDistKDE object using @sdk as
 * kernel and @CV_type as cross-validation method.
 *
 * Returns: (transfer full): the newly created #NcmStatsDistKDE object.
 */
NcmStatsDistKDE *
ncm_stats_dist_kde_new (NcmStatsDistKernel *sdk, NcmStatsDistCV CV_type)
{
  NcmStatsDistKDE *sdkde = g_object_new (NCM_TYPE_STATS_DIST_KDE,
                                         "kernel", sdk,
                                         "CV-type", CV_type,
                                         NULL);
  
  return sdkde;
}

/**
 * ncm_stats_dist_kde_ref:
 * @sdkde: a #NcmStatsDistKDE
 *
 * Increases the reference count of @sdkde.
 *
 * Returns: (transfer full): @sdkde.
 */
NcmStatsDistKDE *
ncm_stats_dist_kde_ref (NcmStatsDistKDE *sdkde)
{
  return g_object_ref (sdkde);
}

/**
 * ncm_stats_dist_kde_free:
 * @sdkde: a #NcmStatsDistKDE
 *
 * Decreases the reference count of @sdkde.
 *
 */
void
ncm_stats_dist_kde_free (NcmStatsDistKDE *sdkde)
{
  g_object_unref (sdkde);
}

/**
 * ncm_stats_dist_kde_clear:
 * @sdkde: a #NcmStatsDistKDE
 *
 * Decreases the reference count of *@sdkde and sets the pointer *@sdkde to NULL.
 *
 */
void
ncm_stats_dist_kde_clear (NcmStatsDistKDE **sdkde)
{
  g_clear_object (sdkde);
}

/**
 * ncm_stats_dist_kde_set_nearPD_maxiter:
 * @sdkde: a #NcmStatsDistKDE
 * @maxiter: maximum number of iterations
 *
 * Sets the maximum number of iterations when finding the
 * nearest positive definite covariance matrix to @maxiter.
 *
 */
void
ncm_stats_dist_kde_set_nearPD_maxiter (NcmStatsDistKDE *sdkde, const guint maxiter)
{
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  
  self->nearPD_maxiter = maxiter;
}

/**
 * ncm_stats_dist_kde_get_nearPD_maxiter:
 * @sdkde: a #NcmStatsDistKDE
 *
 * Returns: maximum number of iterations when finding the nearest positive definite covariance matrix.
 */
guint
ncm_stats_dist_kde_get_nearPD_maxiter (NcmStatsDistKDE *sdkde)
{
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  
  return self->nearPD_maxiter;
}

/**
 * ncm_stats_dist_kde_peek_invU_sample:
 * @sdkde: a #NcmStatsDistKDE
 *
 * Returns: (transfer none) (element-type NcmVector): an array with the transformed ($\left(U^{T}\right)^{-1}v$) sample vectors.
 */
GPtrArray *
ncm_stats_dist_kde_peek_invU_sample (NcmStatsDistKDE *sdkde)
{
  NcmStatsDistKDEPrivate * const self = sdkde->priv;
  
  return self->invUsample;
}

