/* -*- Mode: C; indent-tabs-mode: nil; c-basic-offset: 2; tab-width: 2 -*-  */

/***************************************************************************
 *            ncm_stats_dist_nd_kde_studentt.c
 *
 *  Wed November 07 17:41:47 2018
 *  Copyright  2018  Sandro Dias Pinto Vitenti
 *  <sandro@isoftware.com.br>
 ****************************************************************************/
/*
 * ncm_stats_dist_nd_kde_studentt.c
 * Copyright (C) 2018 Sandro Dias Pinto Vitenti <sandro@isoftware.com.br>
 *
 * numcosmo is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * numcosmo is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * SECTION:ncm_stats_dist_nd_kde_studentt
 * @title: NcmStatsDistNdKDEStudentt
 * @short_description: An N dimensional probability distributions using Multivariate Student's t KDE
 *
 * This object provides the tools to perform a radial basis interpolation
 * in a multidimensional function, using a multivariate Student's t distribution.
 * The goal is to use a polinomial function generated by the interpolation,
 * such that we are able to sample the original functio from this new interpolation function.
 * For more informations about radial basis interpolation,
 * check [https://core.ac.uk/download/pdf/37320748.pdf].
 * A brief description of the radial basis interpolation method can be found below.
 *
 * Given a d-simensional function $g(x): \mathbf{R}^d \rightarrow \mathbf{R}$, a radial basis
 * function $\phi(x)$ is used such that $s(x) = \sum_i^n \lambda \phi(|x-xi|), x \in \mathbf{R}$.
 * The matrix lambda is found such that s(x_i) = g(x_i), being $x_i$ the sample points
 * and the points $\phi(|x-x_i|)$ generate a symmetric $n \times n$ matrix using the radial basis function,
 * in this case the Multivariate Student's t function. Once the Lambda matrix is found,
 * one may use $s(x)$ to sample values from $g(x)$, which is easier to do since $s(x)$ is
 * a polinomial function.
 *
 * We $s(x)$ to be a probability function so we can sample from it. Therefore the Lambda matrix containing the
 * weights is seen as the probability density of our probability function and it must be minimized
 * such that its values are always positive and sum up to one.
 *
 * We use the Multivariate Student's t probability density function as the radial basis function, which is given by:
 * $\phi(x) = \frac{\Gamma[(\nu+p) / 2]}{\Gamma(\nu / 2) \nu^{p / 2} \pi^{p / 2}|\mathbf{\Sigma}|^{1 / 2}}\left[1+\frac{1}{\nu}
 * (\mathbf{x}-\boldsymbol{\mu})^{T} \boldsymbol{\Sigma}^{-1}(\mathbf{x}-\boldsymbol{\mu})\right]^{-(\nu+p) / 2}$,
 * where $\nu$ is the number of degrees of freedom, $p$ is the dimension, $\Sigma$ is the covariant matrix,
 * $\mu$ is the mean (which is only defined if $\nu > 1$) and $x$ are the points to be evaluated.
 *
 * The user must provide the following input values:$p$ - ncm_stats_dist_nd_kde_studentt_new,
 * $LOOCV$ - ncm_stats_dist_nd_kde_studentt_new, $\nu$ - ncm_stats_dist_nd_kde_studentt_new,
 * $vec{x}$ ncm_stats_dist_nd_kde_studentt_prepare_interp.
 *
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "build_cfg.h"

#include "gsl/gsl_sf_result.h"

#include "math/ncm_stats_dist_nd_kde_studentt.h"
#include "math/ncm_stats_vec.h"
#include "math/ncm_c.h"
#include "math/ncm_lapack.h"

#ifndef NUMCOSMO_GIR_SCAN
#include <gsl/gsl_blas.h>
#include <gsl/gsl_min.h>
#include <gsl/gsl_sf_gamma.h>
#include "levmar/levmar.h"
#endif /* NUMCOSMO_GIR_SCAN */

struct _NcmStatsDistNdKDEStudenttPrivate
{
  gdouble nu;
};

enum
{
  PROP_0,
  PROP_NU,
};

G_DEFINE_TYPE_WITH_PRIVATE (NcmStatsDistNdKDEStudentt, ncm_stats_dist_nd_kde_studentt, NCM_TYPE_STATS_DIST_ND);

static void
ncm_stats_dist_nd_kde_studentt_init (NcmStatsDistNdKDEStudentt *dndt)
{
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv = ncm_stats_dist_nd_kde_studentt_get_instance_private (dndt);

  self->nu = 0.0;
}

static void
_ncm_stats_dist_nd_kde_studentt_set_property (GObject *object, guint prop_id, const GValue *value, GParamSpec *pspec)
{
  NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (object);
  /*NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;*/
  
  g_return_if_fail (NCM_IS_STATS_DIST_ND_KDE_STUDENTT (object));
  
  switch (prop_id)
  {
    case PROP_NU:
      ncm_stats_dist_nd_kde_studentt_set_nu (dndt, g_value_get_double (value));
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
}

static void
_ncm_stats_dist_nd_kde_studentt_get_property (GObject *object, guint prop_id, GValue *value, GParamSpec *pspec)
{
  NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (object);
  /*NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;*/
  
  g_return_if_fail (NCM_IS_STATS_DIST_ND_KDE_STUDENTT (object));
  
  switch (prop_id)
  {
    case PROP_NU:
      g_value_set_double (value, ncm_stats_dist_nd_kde_studentt_get_nu (dndt));
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
}

static void
_ncm_stats_dist_nd_kde_studentt_dispose (GObject *object)
{
  /*NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (object);*/
  /*NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;*/
    
  /* Chain up : end */
  G_OBJECT_CLASS (ncm_stats_dist_nd_kde_studentt_parent_class)->dispose (object);
}

static void
_ncm_stats_dist_nd_kde_studentt_finalize (GObject *object)
{
  /* Chain up : end */
  G_OBJECT_CLASS (ncm_stats_dist_nd_kde_studentt_parent_class)->finalize (object);
}

static gdouble _ncm_stats_dist_nd_kde_studentt_get_rot_bandwidth (NcmStatsDistNd *dnd, const guint d, const gdouble n);
static gdouble _ncm_stats_dist_nd_kde_studentt_get_kernel_lnnorm (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, const gdouble n, const gdouble href);
static void _ncm_stats_dist_nd_kde_studentt_prepare_IM (NcmStatsDistNd *dnd, GPtrArray *invUsample, const gint d, const gint n, const gdouble href, const gdouble href2, NcmMatrix *IM);

static gdouble _ncm_stats_dist_nd_kde_studentt_eval (NcmStatsDistNd *dnd, NcmVector *weights, NcmVector *invUy, GPtrArray *invUsample, const gint d, const gint n, const gdouble href, const gdouble href2);
static void _ncm_stats_dist_nd_kde_studentt_kernel_sample (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, NcmVector *y, NcmVector *mu, gdouble href, NcmRNG *rng);
static gdouble _ncm_stats_dist_nd_kde_studentt_kernel_eval_m2lnp (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, NcmVector *x, NcmVector *y, NcmVector *v, const gdouble href, const gdouble href2);

static void
ncm_stats_dist_nd_kde_studentt_class_init (NcmStatsDistNdKDEStudenttClass *klass)
{
  GObjectClass *object_class     = G_OBJECT_CLASS (klass);
  NcmStatsDistNdClass *dnd_class = NCM_STATS_DIST_ND_CLASS (klass);
  
  object_class->set_property = &_ncm_stats_dist_nd_kde_studentt_set_property;
  object_class->get_property = &_ncm_stats_dist_nd_kde_studentt_get_property;
  object_class->dispose      = &_ncm_stats_dist_nd_kde_studentt_dispose;
  object_class->finalize     = &_ncm_stats_dist_nd_kde_studentt_finalize;
  
  g_object_class_install_property (object_class,
                                   PROP_NU,
                                   g_param_spec_double ("nu",
                                                        NULL,
                                                        "nu value of the function",
                                                        1.0, G_MAXDOUBLE, 3.0,
                                                        G_PARAM_READWRITE | G_PARAM_STATIC_NAME | G_PARAM_STATIC_BLURB));

  dnd_class->get_rot_bandwidth = &_ncm_stats_dist_nd_kde_studentt_get_rot_bandwidth;
  dnd_class->get_kernel_lnnorm = &_ncm_stats_dist_nd_kde_studentt_get_kernel_lnnorm;
  dnd_class->prepare_IM        = &_ncm_stats_dist_nd_kde_studentt_prepare_IM;
  
  dnd_class->eval              = &_ncm_stats_dist_nd_kde_studentt_eval;
  dnd_class->kernel_sample     = &_ncm_stats_dist_nd_kde_studentt_kernel_sample;
  dnd_class->kernel_eval_m2lnp = &_ncm_stats_dist_nd_kde_studentt_kernel_eval_m2lnp;
}

static gdouble
_ncm_stats_dist_nd_kde_studentt_f (NcmStatsDistNdKDEStudenttPrivate * const self, const guint d, gdouble chi2)
{
  return pow (1.0 + chi2 / self->nu, -0.5 * (self->nu + d));
}

static gdouble
_ncm_stats_dist_nd_kde_studentt_get_rot_bandwidth (NcmStatsDistNd *dnd, const guint d, const gdouble n)
{
  return pow (4.0 / (n * (d + 2.0)), 1.0 / (d + 4.0));
}

static gdouble
_ncm_stats_dist_nd_kde_studentt_get_kernel_lnnorm (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, const gdouble n, const gdouble href)
{
  NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (dnd);
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;

  const gdouble lg_lnnorm   = lgamma (self->nu / 2.0) - lgamma ((self->nu + d) / 2.0);
  const gdouble chol_lnnorm = 0.5 * ncm_matrix_cholesky_lndet (cov_decomp);
  const gdouble nc_lnnorm   = (d / 2.0) * (ncm_c_lnpi () + log (self->nu));

  return lg_lnnorm + nc_lnnorm + chol_lnnorm + d * log (href);
}

static void
_ncm_stats_dist_nd_kde_studentt_prepare_IM (NcmStatsDistNd *dnd, GPtrArray *Us, const gint d, const gint n, const gdouble href, const gdouble href2, NcmMatrix *IM)
{
  NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (dnd);
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;
  gint i;
  
  for (i = 0; i < n; i++)
  {
    NcmVector *row_i = g_ptr_array_index (Us, i);
    gint j;
    
    ncm_matrix_set (IM, i, i, 1.0);
    
    for (j = i + 1; j < n; j++)
    {
      NcmVector *row_j = g_ptr_array_index (Us, j);
      gdouble m2lnp_ij = 0.0;
      gdouble p_ij;
      gint k;
      
      for (k = 0; k < d; k++)
      {
        m2lnp_ij += gsl_pow_2 (ncm_vector_fast_get (row_i, k) - ncm_vector_fast_get (row_j, k));
      }
      
      p_ij = _ncm_stats_dist_nd_kde_studentt_f (self, d, m2lnp_ij / href2);
      
      ncm_matrix_set (IM, i, j, p_ij);
      ncm_matrix_set (IM, j, i, p_ij);
    }
  }
}

static gdouble
_ncm_stats_dist_nd_kde_studentt_eval (NcmStatsDistNd *dnd, NcmVector *weights, NcmVector *invUy, GPtrArray *invUsample, const gint d, const gint n, const gdouble href, const gdouble href2)
{
  NcmStatsDistNdKDEStudentt *dndt = NCM_STATS_DIST_ND_KDE_STUDENTT (dnd);
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;
  gdouble s = 0.0;
  gdouble c = 0.0;
  gint i;

  for (i = 0; i < n; i++)
  {
    NcmVector *row_i = g_ptr_array_index (invUsample, i);
    gdouble e_i, t, chi2_i = 0.0;
    gint k;

    for (k = 0; k < d; k++)
    {
      chi2_i += gsl_pow_2 (ncm_vector_fast_get (row_i, k) - ncm_vector_fast_get (invUy, k));
    }
    
    e_i = ncm_vector_get (weights, i) * _ncm_stats_dist_nd_kde_studentt_f (self, d, chi2_i / href2);
    t   = s + e_i;
    c  += (s >= e_i) ? ((s - t) + e_i) : ((e_i - t) + s);
    s   = t;
  }
  
  return s;
}

static void
_ncm_stats_dist_nd_kde_studentt_kernel_sample (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, NcmVector *y, NcmVector *mu, gdouble href, NcmRNG *rng)
{
  NcmStatsDistNdKDEStudentt *dndt = NCM_STATS_DIST_ND_KDE_STUDENTT (dnd);
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;
  gdouble chi_scale;
  gint i, ret;

  for (i = 0; i < d; i++)
  {
    const gdouble u_i = gsl_ran_ugaussian (rng->r);
    ncm_vector_set (y, i, u_i);
  }

  /* CblasLower, CblasNoTrans => CblasUpper, CblasTrans */
  ret = gsl_blas_dtrmv (CblasUpper, CblasTrans, CblasNonUnit,
                        ncm_matrix_gsl (cov_decomp), ncm_vector_gsl (y));
  NCM_TEST_GSL_RESULT ("ncm_stats_dist_nd_kde_studentt_sample_mean_scale", ret);

  chi_scale = sqrt (self->nu / gsl_ran_chisq (rng->r, self->nu));

  ncm_vector_scale (y, href * chi_scale);
  ncm_vector_add (y, mu);
}

static gdouble
_ncm_stats_dist_nd_kde_studentt_kernel_eval_m2lnp (NcmStatsDistNd *dnd, NcmMatrix *cov_decomp, const guint d, NcmVector *x, NcmVector *y, NcmVector *v, const gdouble href, const gdouble href2)
{
  NcmStatsDistNdKDEStudentt *dndt               = NCM_STATS_DIST_ND_KDE_STUDENTT (dnd);
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;
  gdouble m2lnp;
  gint ret;
  
  ncm_vector_memcpy (v, x);
  ncm_vector_sub (v, y);
  
  ret = gsl_blas_dtrsv (CblasUpper, CblasTrans, CblasNonUnit,
                        ncm_matrix_gsl (cov_decomp), ncm_vector_gsl (v));
  NCM_TEST_GSL_RESULT ("_ncm_stats_dist_nd_kde_studentt_kernel_eval_m2lnp", ret);
  
  ret = gsl_blas_ddot (ncm_vector_gsl (v), ncm_vector_gsl (v), &m2lnp);
  NCM_TEST_GSL_RESULT ("_ncm_stats_dist_nd_kde_studentt_kernel_eval_m2lnp", ret);
  
  return (self->nu + d) * log1p (m2lnp / href2);
}

/**
 * ncm_stats_dist_nd_kde_studentt_new:
 * @dim: sample space dimension
 * @cv_type: a #NcmStatsDistNdCV
 * @nu: Student-t parameter $\nu$
 *
 * Creates a new #NcmStatsDistNdKDEStudentt object with sample dimension @dim.
 *
 * Returns: a new #NcmStatsDistNdKDEStudentt.
 */
NcmStatsDistNdKDEStudentt *
ncm_stats_dist_nd_kde_studentt_new (const guint dim, const NcmStatsDistNdCV cv_type, const gdouble nu)
{
  NcmStatsDistNdKDEStudentt *dndt = g_object_new (NCM_TYPE_STATS_DIST_ND_KDE_STUDENTT,
                                                  "dimension", dim,
                                                  "CV-type",   cv_type,
                                                  "nu",        nu,
                                                  NULL);
  return dndt;
}

/**
 * ncm_stats_dist_nd_kde_studentt_ref:
 * @dndt: a #NcmStatsDistNdKDEStudentt
 *
 * Increase the reference of @stats_dist_nd_kde_studentt by one.
 *
 * Returns: (transfer full): @stats_dist_nd_kde_studentt.
 */
NcmStatsDistNdKDEStudentt *
ncm_stats_dist_nd_kde_studentt_ref (NcmStatsDistNdKDEStudentt *dndt)
{
  return g_object_ref (dndt);
}

/**
 * ncm_stats_dist_nd_kde_studentt_free:
 * @dndt: a #NcmStatsDistNdKDEStudentt
 *
 * Decrease the reference count of @stats_dist_nd_kde_studentt by one.
 *
 */
void
ncm_stats_dist_nd_kde_studentt_free (NcmStatsDistNdKDEStudentt *dndt)
{
  g_object_unref (dndt);
}

/**
 * ncm_stats_dist_nd_kde_studentt_clear:
 * @dndt: a #NcmStatsDistNdKDEStudentt
 *
 * Decrease the reference count of @stats_dist_nd_kde_studentt by one, and sets the pointer *@stats_dist_nd_kde_studentt to
 * NULL.
 *
 */
void
ncm_stats_dist_nd_kde_studentt_clear (NcmStatsDistNdKDEStudentt **dndt)
{
  g_clear_object (dndt);
}

/**
 * ncm_stats_dist_nd_kde_studentt_set_nu:
 * @dndt: a #NcmStatsDistNdKDEStudentt
 * @nu: the over-smooth factor
 *
 * Sets the over-smooth factor to @nu.
 *
 */
void
ncm_stats_dist_nd_kde_studentt_set_nu (NcmStatsDistNdKDEStudentt *dndt, const gdouble nu)
{
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;

  self->nu = nu;
}

/**
 * ncm_stats_dist_nd_kde_studentt_get_nu:
 * @dndt: a #NcmStatsDistNd
 *
 * Returns: the over-smooth factor.
 */
gdouble
ncm_stats_dist_nd_kde_studentt_get_nu (NcmStatsDistNdKDEStudentt *dndt)
{
  NcmStatsDistNdKDEStudenttPrivate * const self = dndt->priv;

  return self->nu;
}

