
/* Generated data (by glib-mkenums) */

#ifndef __NCM_FIT_NLOPT_ENUM_H__
#define __NCM_FIT_NLOPT_ENUM_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "ncm_fit_nlopt_enum_meta.h" */
GType ncm_fit_nlopt_algorithm_get_type (void) G_GNUC_CONST;
#define NCM_TYPE_FIT_NLOPT_ALGORITHM (ncm_fit_nlopt_algorithm_get_type ())

typedef enum
{
  /*< private >*/
  NCM_FIT_NLOPT_GN_DIRECT = 0,
  NCM_FIT_NLOPT_GN_DIRECT_L = 1,
  NCM_FIT_NLOPT_GN_DIRECT_L_RAND = 2,
  NCM_FIT_NLOPT_GN_DIRECT_NOSCAL = 3,
  NCM_FIT_NLOPT_GN_DIRECT_L_NOSCAL = 4,
  NCM_FIT_NLOPT_GN_DIRECT_L_RAND_NOSCAL = 5,
  NCM_FIT_NLOPT_GN_ORIG_DIRECT = 6,
  NCM_FIT_NLOPT_GN_ORIG_DIRECT_L = 7,
  NCM_FIT_NLOPT_GD_STOGO = 8,
  NCM_FIT_NLOPT_GD_STOGO_RAND = 9,
  NCM_FIT_NLOPT_LD_LBFGS_NOCEDAL = 10,
  NCM_FIT_NLOPT_LD_LBFGS = 11,
  NCM_FIT_NLOPT_LN_PRAXIS = 12,
  NCM_FIT_NLOPT_LD_VAR1 = 13,
  NCM_FIT_NLOPT_LD_VAR2 = 14,
  NCM_FIT_NLOPT_LD_TNEWTON = 15,
  NCM_FIT_NLOPT_LD_TNEWTON_RESTART = 16,
  NCM_FIT_NLOPT_LD_TNEWTON_PRECOND = 17,
  NCM_FIT_NLOPT_LD_TNEWTON_PRECOND_RESTART = 18,
  NCM_FIT_NLOPT_GN_CRS2_LM = 19,
  NCM_FIT_NLOPT_GN_MLSL = 20,
  NCM_FIT_NLOPT_GD_MLSL = 21,
  NCM_FIT_NLOPT_GN_MLSL_LDS = 22,
  NCM_FIT_NLOPT_GD_MLSL_LDS = 23,
  NCM_FIT_NLOPT_LD_MMA = 24,
  NCM_FIT_NLOPT_LN_COBYLA = 25,
  NCM_FIT_NLOPT_LN_NEWUOA = 26,
  NCM_FIT_NLOPT_LN_NEWUOA_BOUND = 27,
  NCM_FIT_NLOPT_LN_NELDERMEAD = 28,
  NCM_FIT_NLOPT_LN_SBPLX = 29,
  NCM_FIT_NLOPT_LN_AUGLAG = 30,
  NCM_FIT_NLOPT_LD_AUGLAG = 31,
  NCM_FIT_NLOPT_LN_AUGLAG_EQ = 32,
  NCM_FIT_NLOPT_LD_AUGLAG_EQ = 33,
  NCM_FIT_NLOPT_LN_BOBYQA = 34,
  NCM_FIT_NLOPT_GN_ISRES = 35,
  NCM_FIT_NLOPT_AUGLAG = 36,
  NCM_FIT_NLOPT_AUGLAG_EQ = 37,
  NCM_FIT_NLOPT_G_MLSL = 38,
  NCM_FIT_NLOPT_G_MLSL_LDS = 39,
  NCM_FIT_NLOPT_LD_SLSQP = 40,
  NCM_FIT_NLOPT_LD_CCSAQ = 41,
  NCM_FIT_NLOPT_GN_ESCH = 42,
  NCM_FIT_NLOPT_NUM_ALGORITHMS = 43,
} NcmFitNloptAlgorithm;

GType ncm_fit_nlopt_result_get_type (void) G_GNUC_CONST;
#define NCM_TYPE_FIT_NLOPT_RESULT (ncm_fit_nlopt_result_get_type ())

typedef enum
{
  /*< private >*/
  NCM_FIT_NLOPT_FAILURE = -1,
  NCM_FIT_NLOPT_INVALID_ARGS = -2,
  NCM_FIT_NLOPT_OUT_OF_MEMORY = -3,
  NCM_FIT_NLOPT_ROUNDOFF_LIMITED = -4,
  NCM_FIT_NLOPT_FORCED_STOP = -5,
  NCM_FIT_NLOPT_SUCCESS = 1,
  NCM_FIT_NLOPT_STOPVAL_REACHED = 2,
  NCM_FIT_NLOPT_FTOL_REACHED = 3,
  NCM_FIT_NLOPT_XTOL_REACHED = 4,
  NCM_FIT_NLOPT_MAXEVAL_REACHED = 5,
  NCM_FIT_NLOPT_MAXTIME_REACHED = 6,
} NcmFitNloptResult;

G_END_DECLS

#endif /* __NCM_FIT_NLOPT_ENUM_H__ */

/* Generated data ends here */

