/***************************************************************************
 *            ncm_binsplit.c
 *
 *  Tue Jan 19 18:28:16 2010
 *  Copyright  2010  Sandro Dias Pinto Vitenti
 *  <vitenti@uel.br>
 ****************************************************************************/
/*
 * numcosmo
 * Copyright (C) Sandro Dias Pinto Vitenti 2012 <vitenti@uel.br>
 * numcosmo is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * numcosmo is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * NcmBinSplit:
 *
 * Binary splitting of rational series in arbitrary precision.
 *
 * A #NcmBinSplit holds the partial sum
 * $$S(n_1, n_2) = \sum_{n=n_1}^{n_2-1} \frac{a(n)}{b(n)} \prod_{k=n_1}^{n} \frac{p(k)}{q(k)}$$
 * of a series with integer $p$, $q$, $a$ and $b$ as the GMP integers $T$, $B$, $Q$ and
 * $P$, with $P = \prod p(k)$, $Q = \prod q(k)$, $B = \prod b(k)$ and $S = T / (BQ)$. The
 * evaluators of a series, #NcmBinSplitEval, are generated by including
 * ncm_binsplit_eval.c, see there. ncm_binsplit_join() combines consecutive ranges, and
 * ncm_binsplit_eval_prec() extends a sum until the next term is below a relative
 * precision.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "build_cfg.h"

#include "ncm/specfunc/ncm_binsplit.h"
#include "ncm/core/ncm_cfg.h"

static gboolean one_init = FALSE;
mpz_t NCM_BINSPLIT_ONE;

/**
 * ncm_binsplit_alloc: (skip)
 * @userdata: the user data passed to the term functions
 *
 * Allocates an empty #NcmBinSplit, with $B = 1$.
 *
 * Returns: (transfer full): a new #NcmBinSplit.
 */
NcmBinSplit *
ncm_binsplit_alloc (gpointer userdata)
{
  NcmBinSplit *bs = g_slice_new (NcmBinSplit);

  bs->userdata = userdata;

  mpz_init (bs->P);
  mpz_init (bs->Q);
  mpz_init (bs->B);
  mpz_init (bs->T);
  mpz_init (bs->temp1);
  mpz_init (bs->temp2);
  mpz_init (bs->temp3);
  mpz_init (bs->temp4);
  bs->bs[0] = bs->bs[1] = NULL;

  mpz_set_ui (bs->B, 1);

  {
    G_LOCK_DEFINE_STATIC (create_lock);
    G_LOCK (create_lock);

    if (!one_init)
    {
      mpz_init (NCM_BINSPLIT_ONE);
      mpz_set_ui (NCM_BINSPLIT_ONE, 1L);
      one_init = TRUE;
    }

    G_UNLOCK (create_lock);
  }

  return bs;
}

/**
 * ncm_binsplit_free: (skip)
 * @bs: a #NcmBinSplit
 *
 * Frees @bs and the buffers it allocated; the user data is not freed.
 */
void
ncm_binsplit_free (NcmBinSplit *bs)
{
  guint i;

  for (i = 0; i < 2; i++)
    if (bs->bs[i] != NULL)
      ncm_binsplit_free (bs->bs[i]);

  mpz_clear (bs->P);
  mpz_clear (bs->Q);
  mpz_clear (bs->B);
  mpz_clear (bs->T);
  mpz_clear (bs->temp1);
  mpz_clear (bs->temp2);
  mpz_clear (bs->temp3);
  mpz_clear (bs->temp4);

  g_slice_free (NcmBinSplit, bs);
}

/**
 * ncm_binsplit_test_next: (skip)
 * @bs: a #NcmBinSplit
 * @bs_eval: the evaluator of the series
 * @nt: the number of terms
 *
 * Evaluates the next @nt terms of the series, without adding them to @bs.
 *
 * Returns: the number of bits by which the sum in @bs exceeds the next @nt terms,
 *   $\log_2 |S / S_\mathrm{next}|$ rounded to integer bit sizes.
 */
glong
ncm_binsplit_test_next (NcmBinSplit *bs, NcmBinSplitEval bs_eval, gulong nt)
{
  size_t s1, s2;

  if (bs->bs[0] == NULL)
    bs->bs[0] = ncm_binsplit_alloc (bs->userdata);

  bs_eval (bs->bs[0], bs->n2, bs->n2 + nt);

  mpz_mul (bs->temp1, bs->bs[0]->B, bs->bs[0]->Q);
  mpz_mul (bs->temp1, bs->temp1, bs->T);

  mpz_mul (bs->temp2, bs->B, bs->P);
  mpz_mul (bs->temp2, bs->temp2, bs->bs[0]->T);

  s1 = mpz_sizeinbase (bs->temp1, 2);
  s2 = mpz_sizeinbase (bs->temp2, 2);

  return (s1 - s2);
}

/**
 * ncm_binsplit_join:
 * @bs: a #NcmBinSplit
 * @bs_l: the sum over $[n_1, n_2)$
 * @bs_r: the sum over $[n_2, n_3)$
 *
 * Sets @bs to the sum over $[n_1, n_3)$. @bs may be @bs_l or @bs_r; the two ranges must
 * be consecutive.
 */
void
ncm_binsplit_join (NcmBinSplit *bs, NcmBinSplit *bs_l, NcmBinSplit *bs_r)
{
  mpz_ptr temp5 = bs->P; /* scratch, once both P have been used */

  g_assert ((bs != bs_l) || (bs != bs_r));
  g_assert (bs_l->n2 == bs_r->n1);

  mpz_mul (bs->temp1, bs_l->P, bs_r->P);
  mpz_mul (bs->temp2, bs_l->Q, bs_r->Q);
  mpz_mul (bs->temp3, bs_l->B, bs_r->B);

  mpz_mul (bs->temp4, bs_l->B, bs_l->P);
  mpz_mul (bs->temp4, bs->temp4, bs_r->T);

  mpz_mul (temp5, bs_r->B, bs_r->Q);
  mpz_mul (temp5, temp5, bs_l->T);

  mpz_add (bs->temp4, bs->temp4, temp5);

  mpz_swap (bs->P, bs->temp1);
  mpz_swap (bs->Q, bs->temp2);
  mpz_swap (bs->B, bs->temp3);
  mpz_swap (bs->T, bs->temp4);

  bs->n1 = bs_l->n1;
  bs->n2 = bs_r->n2;

  return;
}

/**
 * ncm_binsplit_eval_join: (skip)
 * @bs: a #NcmBinSplit
 * @bs_eval: the evaluator of the series
 * @nt: the number of terms
 *
 * Adds the next @nt terms of the series to @bs.
 */
void
ncm_binsplit_eval_join (NcmBinSplit *bs, NcmBinSplitEval bs_eval, gulong nt)
{
  gulong n3 = bs->n2 + nt;
  gulong nl = (bs->n2 + n3) / 2;

  if (bs->bs[0] == NULL)
    bs->bs[0] = ncm_binsplit_alloc (bs->userdata);

  if (bs->bs[1] == NULL)
    bs->bs[1] = ncm_binsplit_alloc (bs->userdata);

  if (nt == 1)
  {
    bs_eval (bs->bs[1], nl, n3);
    ncm_binsplit_join (bs, bs, bs->bs[1]);
  }
  else
  {
    bs_eval (bs->bs[0], bs->n2, nl);
    bs_eval (bs->bs[1], nl, n3);

    ncm_binsplit_join (bs->bs[0], bs->bs[0], bs->bs[1]);
    ncm_binsplit_join (bs, bs, bs->bs[0]);
  }

  return;
}

/**
 * ncm_binsplit_eval_prec: (skip)
 * @bs: a #NcmBinSplit
 * @bs_eval: the evaluator of the series
 * @step: the number of terms added at a time
 * @prec: the relative precision, in bits
 *
 * Sets @bs to the sum of the first @step terms, then adds @step terms at a time until
 * the next term is @prec bits below the sum, see ncm_binsplit_test_next().
 *
 * Returns: the number of terms summed.
 */
gulong
ncm_binsplit_eval_prec (NcmBinSplit *bs, NcmBinSplitEval bs_eval, gulong step, glong prec)
{
  gulong tstep = 0;

  bs_eval (bs, 0, step);
  tstep += step;

  while (ncm_binsplit_test_next (bs, bs_eval, 1) < prec)
  {
    ncm_binsplit_eval_join (bs, bs_eval, step);
    tstep += step;
  }

  return tstep;
}

/**
 * ncm_binsplit_get: (skip)
 * @bs: a #NcmBinSplit
 * @res: the output, at its own precision
 *
 * Computes the sum $T / (BQ)$ into @res, rounding toward $-\infty$.
 */
void
ncm_binsplit_get (NcmBinSplit *bs, mpfr_t res)
{
  mpfr_set_z (res, bs->T, GMP_RNDD);
  mpfr_div_z (res, res, bs->B, GMP_RNDD);
  mpfr_div_z (res, res, bs->Q, GMP_RNDD);

  return;
}

/**
 * ncm_binsplit_get_q: (skip)
 * @bs: a #NcmBinSplit
 * @q: the output
 *
 * Sets @q to the sum $T / (BQ)$, in lowest terms.
 */
void
ncm_binsplit_get_q (NcmBinSplit *bs, mpq_t q)
{
  mpz_set (mpq_numref (q), bs->T);
  mpz_set (mpq_denref (q), bs->B);
  mpz_mul (mpq_denref (q), mpq_denref (q), bs->Q);
  mpq_canonicalize (q);

  return;
}

/**
 * ncm_binsplit_get_d: (skip)
 * @bs: a #NcmBinSplit
 * @rnd: the rounding mode
 *
 * Returns: the sum $T / (BQ)$ as a double, computed with 64-bit intermediates.
 */
gdouble
ncm_binsplit_get_d (NcmBinSplit *bs, mp_rnd_t rnd)
{
  MPFR_DECL_INIT (res, 64);
  mpfr_set_z (res, bs->T, rnd);
  mpfr_div_z (res, res, bs->B, rnd);
  mpfr_div_z (res, res, bs->Q, rnd);

  return mpfr_get_d (res, rnd);
}

